### ISSUE TITLE
[Bug][Image] isSupported() in LÖVE 0.10.0

### ISSUE THREAD

**Issue by Ranguna** [Positive07/material-love#19]
The command [`isSupported()`](https://love2d.org/wiki/love.graphics.isSupported) has been removed in LÖVE 0.10.0. [Line 4](https://github.com/Positive07/material-love/blob/master/libs/image.lua#L4)
It changed to [`getSupported()`](https://love2d.org/wiki/love.graphics.getSupported) and the `"shader"` argument has been removed too, so `"multicanvasformats"` should probably be used since it checks for OpenGL ES 3 hardware.

**Comment by pablomayobre** [comment]
Material-Love was not written for 0.10.0 in mind, and currently I'm not working on it, I might revise it later, I think this is not the only change I should make to it to fully support 0.10.0 so please keep reporting if there are any other issues, I'll come back and fix it when I have time

**Comment by slime73** [comment]
> "multicanvasformats" should probably be used since it checks for OpenGL ES 3 hardware.

Unless the code actually uses multi-canvas rendering with different Canvas formats in each active Canvas, this is not necessary at all. All devices that support LÖVE 0.10.0 will unconditionally support shaders and canvases.

"multicanvasformats" is specifically and only for this:

``` Lua
canvas1 = love.graphics.newCanvas(w, h, "normal") -- Or some other format
canvas2 = love.graphics.newCanvas(w, h, "rgba16f") -- Or some other format that's different than the one above

function love.draw()
    love.graphics.setCanvas(canvas1, canvas2) -- multi-canvas rendering
    -- do some drawing here
    love.graphics.setCanvas()
    -- etc.
end
```

**Comment by pablomayobre** [comment]
Well that should fix it. Again I can't test 0.10.0 so if anyone tries it and it doesnt work feel free to reopen this. Also if anyother bug is found on 0.10.0 report it and I'll try to fix them (again without testing)
