### ISSUE TITLE
[Enhancement][Roundrect] Compatibility with LÖVE 0.10.0

### ISSUE THREAD

**Issue by pablomayobre** [Positive07/material-love#22]
LÖVE 0.10.0 added radius values to the `love.graphics.rectangle` function, we should try to match that API so that we can easily replace rounrect.lua with this function on newer systems.

The fix is silly I'll try to do it tonight. I don't really like LÖVE's API though, it is really rare to have different radius in X and Y, I prefere the roundrect one where you specify a radius for each corner, LÖVE can't do this though, all corner share the same both radius in X and Y.

**Comment by Ranguna** [comment]
How about keeping material love's roundrect functions the same ?
Since they allows user the possibility to set radius to each corner whilst love's rectangle function only allows two radius for all corners.

**Comment by pablomayobre** [comment]
If this is desired then I have no problem on keeping it like that.

Actually LÖVE 0.9.0 would be able to use roundrect while 0.10.0 would be able to use both so it should be better

I'm closing this now, feel free to reopen if needed

**Comment by Ranguna** [comment]
As we can see in [this example](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3UWdmRm15cGR2TGM/components_cards_action4.png), the radius on the top corners are smaller than the radius on the bottom corners, so I belive it's best to keep this the way it is or else we won't be able to produce this kind of effect.

**Comment by pablomayobre** [comment]
Mmm... I think that image is actually wrong, the spec actually says that [buttons](https://material.google.com/components/buttons.html#buttons-style) and [cards](https://material.google.com/components/cards.html#cards-usage) should have corners with a radius of 2dp

But it will be useful anyway so I'm gonna leave it
