### ISSUE TITLE
[Enhancement][demo] Update demo.love to the latest version of LÖVE

### ISSUE THREAD

**Issue by DNS** [Positive07/material-love#24]
![untitled](https://cloud.githubusercontent.com/assets/37093/16450671/7aad8b30-3e28-11e6-8d8f-b774fefe27eb.png)
![untitled2](https://cloud.githubusercontent.com/assets/37093/16450674/80df92f0-3e28-11e6-877b-d804143171a8.png)

**Comment by pablomayobre** [comment]
The demo is outdated as has been stated in #21 you could try and open the .love file and put an updated version of the library, but it will most probably break.

Currently I've no time to fix the demo, and I'm not sure I would, I would prefer to write a new one with all the available stuff.

Also I'm writing a new library which does all stuff Material-Love does, which will be called Material World.

I accept pull-requests though, there is a [test branch](https://github.com/Positive07/material-love/tree/test)

**Comment by pablomayobre** [comment]
Note: Material-Love should work with 0.10.1 directly without changes, the problem is that the demo uses outdated API's some of which I haven't documented either. Material-World is still in progress so I won't probably revisit the demo

**Comment by pablomayobre** [comment]
Okey, demo is updated, I also made several changes to the library so you better check it out!
