### ISSUE TITLE
[Feature] Loading bar / spinner

### ISSUE THREAD

**Issue by pablomayobre** [Positive07/material-love#8]
This is something I want and I'll probably implement

Just find the two angles that define the spinner arc and draw all the points with the specified precision. The problem is finding the two points.

The loading bar is easier and may not meet this library scope (if I'm correct is just an easing function)

**Comment by Mrmaxmeier** [comment]
I've implemented a spinner / loading bar element over [here](https://github.com/Mrmaxmeier/material-love). Currently there is a drawing function and a kind of management object for spinners and bars.
I could create a pull request with only the drawing functions.

**Comment by pablomayobre** [comment]
Wow! great... (You are awesome Mrmaxmeier)... let me check it out and see what I'll do about it!

EDIT: Well I read your code but I'm not sure that gives the effect I'm looking for, I was thinking about [this](http://codepen.io/mrrocks/pen/EiplA)

What you have done is pretty neat for progress but I'm more interested in loading (it's freaking animation is neat but hard).

**Comment by pablomayobre** [comment]
Mrmaxmeier, I would be interested in that smooth image thing... nice shader you've got there haha.
Does it give [this](https://www.google.com/design/spec/patterns/loading-images.html#loading-images-loading-images) effect?

**Comment by Mrmaxmeier** [comment]
Yup, tried to implement the spec.
Im currently not using the right color modifications though.
[current version](http://imgur.com/DNKRcHD)

**Comment by pablomayobre** [comment]
Okey I liked both haha the progress is pretty neat! But not in scope sorry.

Soon I'll start working on a material-ui but till then I would prefer to keep this simple.

Can I ask you to make a PR with that image thing? It is sweet!

**Comment by pablomayobre** [comment]
The only problem I have with it is that you are using Flux and I dont want to have dependencies, I would like to give that choice to the user. The solution is as simple as implementing the tweening directly in Lua so if you dont want to do it your self I can do it.

**Comment by pablomayobre** [comment]
Okey @Mrmaxmeier I modified your code so that it doesnt use Flux, can you test it out? My computer doesnt support shaders so I cant.

``` lua
local image = {}

local ease = function (time,ftime)
    local p = time/ftime
    local e = -p * (p - 2)
    return e
end

local hsvShader = love.graphics.newShader[[
vec3 rgb2hsv(vec3 c)
{
    vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
    vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));
    vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));
    float d = q.x - min(q.w, q.y);
    float e = 1.0e-10;
    return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);
}

vec3 hsv2rgb(vec3 c)
{
    vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

extern number hMod;
extern number sMod;
extern number vMod;
extern number opacity;

vec4 effect( vec4 color, Image texture, vec2 texture_coords, vec2 screen_coords ){
    vec4 pixel = Texel(texture, texture_coords );//This is the current pixel color
    vec3 hsv = rgb2hsv(pixel.rgb);
    hsv.r *= hMod;
    hsv.g *= sMod;
    hsv.b *= vMod;
    pixel = vec4(hsv2rgb(hsv).rgb, pixel.a * opacity);
    return pixel * color;
}
]]

function image.new(img)
    return {
        img = img,
        hMod = 1,
        sMod = 0,
        vMod = 0,
        opacity = 0,
        fading = false,
        times = {0,-0.3,-0.1},
        fadein = image.fadein,
        update = image.update,
        draw = image.draw
    }
end

function image.update(state,dt)
    if state.fading then
        local eases = {}
        for i=1, 3 do
            state.times[i] = state.times[i] - dt

            if state.times[i] > 0 then
                eases[i] = ease(state.times,1)
            else
                eases[i] = 0
            end
        end

        state.sMod = math.min(eases[1],1)
        state.vMod = math.min(eases[2],1)
        state.opacity = math.min(eases[3],1)
    end
end

function image.fadein(state)
    state.opacity = 0.0
    state.sMod = 0.0
    state.vMod = 0.0

    state.fading = true
end

function image.draw(state, x, y, sx, sy)
    if not sx then sx = state.img:getWidth() end
    if not sy then sy = state.img:getHeight() end

    hsvShader:send("hMod", state.hMod)
    hsvShader:send("sMod", state.sMod)
    hsvShader:send("vMod", state.vMod)
    hsvShader:send("opacity", state.opacity)

    love.graphics.setShader(hsvShader)
    love.graphics.draw(state.img, x, y, 0, sx/state.img:getWidth(), sy/state.img:getHeight())
    love.graphics.setShader()
end

return image
```

If this works I'll place it in the next commit with proper credits :smile:

PS: I deleted the default externs so it should now work on Android and iOS too :wink:

**Comment by Mrmaxmeier** [comment]
I've already updated it with a different easing function :P d119314500b36b9d965199f065d64008b38884da
without flux the code is much cleaner because you can just draw an image with time  0 -> ∞ and it'll stop fading at time 1

**Comment by pablomayobre** [comment]
Nice! Can I commit this? No need for a PR, it will give you headaches to make a PR just for this file haha... Also I would like to make some minor changes. Are you fine with it?

**Comment by Mrmaxmeier** [comment]
yes, of course.
git cherry-picking is a pain, because i squashed different stuff in a commit :smile:

**Comment by pablomayobre** [comment]
Yeah, also if you wanted to branch it, it copies all the commit... It's a pain haha. It will be there in the next commit (together with a huge bunch of changes!)

**Comment by pablomayobre** [comment]
Okey I implemented the spinners!! SO MUCH MATH ugh... Well anyway, they are in the next commit. I'm closing this

**Comment by pablomayobre** [comment]
@Mrmaxmeier Can I ask you a favor? I need an image just like [this one](http://imgur.com/DNKRcHD), but less bloated, for the wiki page on "Image Transition". So just the image transition (The shadow may stay, it doesnt bother) with a white background, but without the spinner and loading bar.

I would do this myself but my computer doesnt support shaders u.u

**Comment by Mrmaxmeier** [comment]
sure, http://imgur.com/cEaGWtL

**Comment by pablomayobre** [comment]
You rock!
